env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2020 # Включает поддержку конструкции import.meta.url
  sourceType: module
rules: { no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] } # разрешает подчёркивание в именах только для двух констант
